<div class="sidebar col-sm-2">
    <div class="title">
        <div class="card">
            <img src="STYLE/fotaPerfil.jpeg" alt="Avatar" style="width:100%">
            <div class="container">
                <h4 class="fonteBranca"><b>Shoveler</b></h4>
            </div>
        </div>
        <!--<img src="fotaPerfil.jpeg" class="ftPerfil">                
        <h3 class="nomePerfil">Shoveler</h3>-->
        <div class="perfil">
            <form class="pagePerfil" method="get" action="me.php">
                <button type="submit">Ver perfil</button>
            </form>
            <h3>Minhas mesas:</h3>
            <ul>
                <li><a href="pgMesa.php">Mesa 1</a></li>
                <li><a href="pgMesa.php">Mesa 2</a></li>
                <li><a href="pgMesa.php">Mesa 3</a></li>
            </ul>
        </div>
    </div>
</div>